openapi: 3.0.0
info:
  title: Macrometa API Reference Activity Metrics API
  version: 0.17.17
  description: API reference for the Macrometa Global Data Network.
  license:
    name: Macrometa License, Version 2.0
servers:
- url: https://api-play.paas.macrometa.io
  description: GDN API
host: api-play.paas.macrometa.io
security:
- ApiKeyAuth: []
- BearerAuth: []
tags:
- name: Metrics
  description: Retrieve EDS metrics data
paths:
  /api/es/v1/metrics:
    get:
      tags:
      - Metrics
      summary: Retrieve metrics data via WebSocket
      description: Understanding the performance and usage of the EDS is vital. Metrics provide insights that help identify issues, analyze trends, optimize operations, and measure effectiveness.
      operationId: get-metrics-ws
      parameters:
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/type'
      - $ref: '#/components/parameters/name'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/order'
      - $ref: '#/components/parameters/x-customer-id'
      responses:
        '200':
          description: Successfully returned the status of the service.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetricsResponse'
              examples:
                Event delivery service metrics:
                  value:
                    cid: cust-id
                    evntdlv: 31468092
                    evntdlvrt: 0
                    evnterrrt: 0
                    evntpub: 0
                    evntpubrt: 0
                    evntsz: 39573481965
                    evntszrt: 0
                    fb: _system
                    mxconn: 0
                    mxqry: 0
                    ssesub: 0
                    str: 3
                    strm:
                    - stream1:
                        conn: 0
                        evntdlvrt: 0
                        evnterrrt: 0
                        evntszrt: 0
                        qry: 0
                    ts: 1720569636000
                    type: day
                    wssub: 0
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetErrorResponse'
      security:
      - api_key: []
  /api/es/sse/v1/metrics:
    get:
      tags:
      - Metrics
      summary: Retrieve metrics data via SSE
      description: Understanding the performance and usage of the EDS is vital. Metrics provide insights that help identify issues, analyze trends, optimize operations, and measure effectiveness.
      operationId: get-metrics-sse
      parameters:
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/end'
      - $ref: '#/components/parameters/type'
      - $ref: '#/components/parameters/name'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/sort'
      - $ref: '#/components/parameters/order'
      - $ref: '#/components/parameters/x-customer-id'
      responses:
        '200':
          description: Successfully returned the status of the service.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetricsResponse'
              examples:
                Event delivery service metrics:
                  value:
                    cid: cust-id
                    evntdlv: 31468092
                    evntdlvrt: 0
                    evnterrrt: 0
                    evntpub: 0
                    evntpubrt: 0
                    evntsz: 39573481965
                    evntszrt: 0
                    fb: _system
                    mxconn: 0
                    mxqry: 0
                    ssesub: 0
                    str: 3
                    strm:
                    - stream1:
                        conn: 0
                        evntdlvrt: 0
                        evnterrrt: 0
                        evntszrt: 0
                        qry: 0
                    ts: 1720569636000
                    type: day
                    wssub: 0
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetErrorResponse'
      security:
      - api_key: []
  /api/ds/v1/metrics:
    get:
      summary: Retrieve metrics data
      description: Returns metrics data for a given time period. If the data for a particular period is 'null', then metrics cannot be calculated for that time period. For example, accuracy cannot be calculated if there were no visits for that day.
      operationId: getMetricsData
      tags:
      - Metrics
      security:
      - ApiKeyAuth: []
      parameters:
      - name: start
        in: query
        description: The start date used for querying metrics data. Must be provided in RFC3339 date-time format and UTC.
        required: false
        example: YYYY-MM-DDTHH:MM:SSZ
        schema:
          type: string
          format: date-time
      - name: end
        in: query
        description: The end date used for querying metrics data. Must be provided in RFC3339 date-time format and UTC.
        required: false
        example: YYYY-MM-DDTHH:MM:SSZ
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Successfully retrieved metrics data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsResponse_2'
        '400':
          description: Bad request
        '401':
          description: Authorization failure due to invalid authentication credentials.
  /api/ds/v1/metrics/topn/visits:
    get:
      summary: Retrieve top visits count with their visitor IDs.
      description: Returns top visits count with their visitor IDs for a given time period.
      operationId: getTopNVisitsData
      tags:
      - Metrics
      security:
      - ApiKeyAuth: []
      parameters:
      - name: n
        in: query
        description: Number of top visits data to return to.
        required: true
        example: 'true'
        schema:
          type: number
      - name: isBot
        in: query
        description: Flag to include bots in top n visits count.
        required: false
        example: 'false'
        schema:
          type: boolean
      - name: start
        in: query
        description: The start date used for querying visits data. Must be provided in RFC3339 date-time format and be in UTC. The default start time is 24 hours before the current time.
        required: false
        example: YYYY-MM-DDTHH:MM:SSZ
        schema:
          type: string
          format: date-time
      - name: end
        in: query
        description: The end date used for querying visits data. Must be provided in RFC3339 date-time format and be in UTC. The default end time is the current time.
        required: false
        example: YYYY-MM-DDTHH:MM:SSZ
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Successfully retrieved metrics data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopNVisitsResponse'
        '400':
          description: Bad request.
        '401':
          description: Authorization failure due to invalid authentication credentials.
  /api/ds/v1/metrics/traffic:
    get:
      summary: Retrieve visitor traffic metrics
      description: "Returns the visitor traffic over a period of time.\n\nThe traffic metrics are reported in five-minute intervals:\n- Total number of human visitors\n- Total number of good bot visitors\n- Total number of bad bot visitors\n- Total number of unknown bot visitors\n\n_Human visitors_ are non-bot visitors. _Good bots_ are a list of well-known bots, including Googlebot, Bingbot, and so on).\n_Bad bots_ are a list of known bad bots, including Grinchbots, AhrefsBot, and so on. _Unknown bots_ are visitors that are likely \nbots but are not in the good or bad bot lists.\n"
      operationId: getTrafficData
      tags:
      - Metrics
      security:
      - ApiKeyAuth: []
      parameters:
      - name: start
        in: query
        description: The start date used for querying visitor traffic data. Must be provided in RFC3339 date-time format and UTC. The default start time is 24 hours before the current time.
        required: false
        example: YYYY-MM-DDTHH:MM:SSZ
        schema:
          type: string
          format: date-time
      - name: end
        in: query
        description: The end date used for querying visitor traffic data. Must be provided in RFC3339 date-time format and UTC. The default end time is the current time.
        required: false
        example: YYYY-MM-DDTHH:MM:SSZ
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Successfully retrieved traffic metrics data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrafficResponse'
        '400':
          description: Bad request.
        '401':
          description: Authorization failure due to invalid authentication credentials.
  /api/ds/v1/metrics/device/types:
    get:
      summary: Retrieve the different device types for the visits
      description: 'Returns the device types over a period of time.

        '
      operationId: getDeviceTypeData
      tags:
      - Metrics
      security:
      - ApiKeyAuth: []
      parameters:
      - name: start
        in: query
        description: The start date used for querying the device data. Must be provided in RFC3339 date-time format and UTC. The default start time is 24 hours from current time.
        required: false
        example: YYYY-MM-DDTHH:MM:SSZ
        schema:
          type: string
          format: date-time
      - name: end
        in: query
        description: The end date used for querying the device data. Must be provided in RFC3339 date-time format and UTC. The default end time is the current time.
        required: false
        example: YYYY-MM-DDTHH:MM:SSZ
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Successfully retrieved device metrics data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceTypeResponse'
        '400':
          description: Bad request.
        '401':
          description: Authorization failure due to invalid authentication credentials.
  /api/prerender/v1/metrics/percentiles/responsetime:
    get:
      summary: 'Get response time percentiles '
      tags:
      - Metrics
      description: Returns response time percentiles within a specific time range, optionally filtered by URL pattern and response code. Required query parameters include from and to, denoting the epoch time range in seconds. An optional urlRegex parameter allows filtering by URL patterns, while responseCode filters the metrics by HTTP response code. The endpoint returns the 90th, 95th, and 99th percentiles of response times. A customerId header is required for authentication.
      parameters:
      - schema:
          type: number
        in: query
        name: from
        required: true
        description: Timestamp (in seconds) used as the initial time for filtering.
      - schema:
          type: number
        in: query
        name: to
        required: true
        description: Timestamp (in seconds) used as the final time for filtering.
      - schema:
          type: string
        in: query
        name: urlRegex
        required: false
        description: Regex of URL path.
      - schema:
          type: number
        in: query
        name: responseCode
        required: false
        description: Response code for filtering.
      - schema:
          type: string
        in: header
        name: x-photoniq-customerid
        required: true
        description: Customer unique identifier.
      responses:
        '200':
          description: Response time percentiles fetched successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  p90:
                    type: number
                    description: The 90th percentile value. This represents the value below which 90% of the data points fall.
                  p95:
                    type: number
                    description: The 95th percentile value. This represents the value below which 95% of the data points fall.
                  p99:
                    type: number
                    description: The 99th percentile value. This represents the value below which 99% of the data points fall.
                description: Response time percentiles fetched successfully.
                example:
                  p90: 7355
                  p95: 8007
                  p99: 10517
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                description: Bad request.
                properties:
                  status:
                    type: string
                    description: Error status.
                  message:
                    type: string
                    description: Error message.
                required:
                - status
                - message
                example:
                  status: ERROR
                  message: Header x-photoniq-customerid is required.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                description: Internal server error.
                properties:
                  status:
                    type: string
                    description: Error status.
                  message:
                    type: string
                    description: Error message.
                required:
                - status
                - message
                example:
                  status: ERROR
                  message: Internal server error.
  /api/prerender/v1/metrics/percentiles/responsetime/{origin}:
    get:
      summary: Get response time percentiles  by origin
      tags:
      - Metrics
      description: Returns response time percentiles within a specific time range, optionally filtered by URL pattern and response code. Required query parameters include from and to, denoting the epoch time range in seconds. An optional urlRegex parameter allows filtering by URL patterns, while responseCode filters the metrics by HTTP response code. The endpoint returns the 90th, 95th, and 99th percentiles of response times. A customerId header is required for authentication.
      parameters:
      - schema:
          type: number
        in: query
        name: from
        required: true
        description: Timestamp (in seconds) used as the initial time for filtering.
      - schema:
          type: number
        in: query
        name: to
        required: true
        description: Timestamp (in seconds) used as the final time for filtering.
      - schema:
          type: string
        in: query
        name: urlRegex
        required: false
        description: Regex of URL path.
      - schema:
          type: number
        in: query
        name: responseCode
        required: false
        description: Response code for filtering.
      - schema:
          type: string
          minLength: 1
        example: www.origin.com
        in: path
        name: origin
        required: true
        description: Origin hostname.
      - schema:
          type: string
        in: header
        name: x-photoniq-customerid
        required: true
        description: Customer unique identifier.
      responses:
        '200':
          description: Response time percentiles fetched successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  p90:
                    type: number
                    description: The 90th percentile value. This represents the value below which 90% of the data points fall.
                  p95:
                    type: number
                    description: The 95th percentile value. This represents the value below which 95% of the data points fall.
                  p99:
                    type: number
                    description: The 99th percentile value. This represents the value below which 99% of the data points fall.
                description: Response time percentiles fetched successfully.
                example:
                  p90: 7355
                  p95: 8007
                  p99: 10517
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                description: Bad request.
                properties:
                  status:
                    type: string
                    description: Error status.
                  message:
                    type: string
                    description: Error message.
                required:
                - status
                - message
                example:
                  status: ERROR
                  message: Header x-photoniq-customerid is required.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                description: Internal server error.
                properties:
                  status:
                    type: string
                    description: Error status.
                  message:
                    type: string
                    description: Error message.
                required:
                - status
                - message
                example:
                  status: ERROR
                  message: Internal server error.
  /api/prerender/v1/metrics/stats/prefetch/{origin}:
    get:
      summary: Get prefetch statistics
      tags:
      - Metrics
      description: Returns the latest prefetch statistics associated with the origin.
      parameters:
      - schema:
          type: string
          enum:
          - queued
          - in_progress
          - completed
          - canceled
        in: query
        name: status
        required: false
        description: Prefetch status.
      - schema:
          type: integer
          minimum: 0
          default: 0
        in: query
        name: offset
        required: false
        description: Pagination offset.
      - schema:
          type: integer
          minimum: 1
          default: 1000
          maximum: 1000
        in: query
        name: limit
        required: false
        description: Pagination limit.
      - schema:
          type: string
          minLength: 1
        example: www.origin.com
        in: path
        name: origin
        required: true
        description: Origin hostname.
      - schema:
          type: string
        in: header
        name: x-photoniq-customerid
        required: true
        description: Customer unique identifier.
      responses:
        '200':
          description: Prefetch statistics fetched successfully.
          content:
            application/json:
              schema:
                type: array
                description: Prefetch statistics fetched successfully.
                items:
                  type: object
                  properties:
                    prefetchType:
                      type: string
                      enum:
                      - manual
                      - scheduled
                      description: Method of prefetching.
                    prefetchStatus:
                      type: string
                      description: Current status of prefetching.
                    totalPrefetched:
                      type: number
                      description: Count of total URLs prefetched.
                    totalCompleted:
                      type: number
                      description: Count of URLs successfully prefetched.
                    totalRetrying:
                      type: number
                      description: Count of URLs retrying prefetch.
                    totalQueued:
                      type: number
                      description: Count of URLs queued for prefetch.
                    totalFailed:
                      type: number
                      description: Count of URLs where prefetch failed.
                    createdAt:
                      type: number
                      description: Unix timestamp of prefetch trigger creation.
                  required:
                  - prefetchType
                  - prefetchStatus
                  - totalPrefetched
                  - totalCompleted
                  - totalRetrying
                  - totalQueued
                  - totalFailed
                  - createdAt
                example:
                - prefetchType: scheduled
                  prefetchStatus: in_progress
                  totalPrefetched: 500
                  totalCompleted: 400
                  totalRetrying: 3
                  totalQueued: 95
                  totalFailed: 2
                  createdAt: 1672542000
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                description: Bad request.
                properties:
                  status:
                    type: string
                    description: Error status.
                  message:
                    type: string
                    description: Error message.
                required:
                - status
                - message
                example:
                  status: ERROR
                  message: Header x-photoniq-customerid is required.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                description: Internal server error.
                properties:
                  status:
                    type: string
                    description: Error status.
                  message:
                    type: string
                    description: Error message.
                required:
                - status
                - message
                example:
                  status: ERROR
                  message: Internal server error.
  /api/prerender/v1/metrics/stats/render:
    get:
      summary: Get render-stats metrics
      tags:
      - Metrics
      description: 'Returns render stats metrics within a specified time range. This endpoint expects two required query parameters: from and to, representing the start and end of the time range in epoch seconds. The request must include a customerId header for authentication.'
      parameters:
      - schema:
          type: number
        in: query
        name: from
        required: true
        description: Timestamp (in seconds) used as the initial time for filtering.
      - schema:
          type: number
        in: query
        name: to
        required: true
        description: Timestamp (in seconds) used as the final time for filtering.
      - schema:
          type: string
        in: header
        name: x-photoniq-customerid
        required: true
        description: Customer unique identifier.
      responses:
        '200':
          description: Render statistics fetched successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalPrefetch:
                    type: number
                    description: The total number of prefetched requests.
                  totalCacheHits:
                    type: number
                    description: The total number of requests that were successfully served from the cache.
                  totalCacheMisses:
                    type: number
                    description: The total number of requests that were not served from the cache.
                  totalResponseSize:
                    type: number
                    description: The total size of all responses sent, measured in bytes.
                  totalOriginsRenderingFor:
                    type: number
                    description: The total number of unique origins for which rendering was performed.
                  totalRenders:
                    type: number
                    description: The total number of render operations performed.
                  totalFailed:
                    type: number
                    description: The total number of render operations that failed.
                description: Render statistics fetched successfully.
                example:
                  totalPrefetch: 75
                  totalCacheHits: 6
                  totalCacheMisses: 83
                  totalResponseSize: 30340237
                  totalOriginsRenderingFor: 3
                  totalRenders: 87
                  totalFailed: 2
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                description: Bad request.
                properties:
                  status:
                    type: string
                    description: Error status.
                  message:
                    type: string
                    description: Error message.
                required:
                - status
                - message
                example:
                  status: ERROR
                  message: Header x-photoniq-customerid is required.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                description: Internal server error.
                properties:
                  status:
                    type: string
                    description: Error status.
                  message:
                    type: string
                    description: Error message.
                required:
                - status
                - message
                example:
                  status: ERROR
                  message: Internal server error.
  /api/prerender/v1/metrics/stats/render/{origin}:
    get:
      summary: Get render-stats metrics by origin
      tags:
      - Metrics
      description: 'Returns render stats metrics within a specified time range. This endpoint expects two required query parameters: from and to, representing the start and end of the time range in epoch seconds. The request must include a customerId header for authentication.'
      parameters:
      - schema:
          type: number
        in: query
        name: from
        required: true
        description: Timestamp (in seconds) used as the initial time for filtering.
      - schema:
          type: number
        in: query
        name: to
        required: true
        description: Timestamp (in seconds) used as the final time for filtering.
      - schema:
          type: string
          minLength: 1
        example: www.origin.com
        in: path
        name: origin
        required: true
        description: Origin hostname.
      - schema:
          type: string
        in: header
        name: x-photoniq-customerid
        required: true
        description: Customer unique identifier.
      responses:
        '200':
          description: Render statistics fetched successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalPrefetch:
                    type: number
                    description: The total number of prefetched requests.
                  totalCacheHits:
                    type: number
                    description: The total number of requests that were successfully served from the cache.
                  totalCacheMisses:
                    type: number
                    description: The total number of requests that were not served from the cache.
                  totalResponseSize:
                    type: number
                    description: The total size of all responses sent, measured in bytes.
                  totalOriginsRenderingFor:
                    type: number
                    description: The total number of unique origins for which rendering was performed.
                  totalRenders:
                    type: number
                    description: The total number of render operations performed.
                  totalFailed:
                    type: number
                    description: The total number of render operations that failed.
                description: Render statistics fetched successfully.
                example:
                  totalPrefetch: 75
                  totalCacheHits: 6
                  totalCacheMisses: 83
                  totalResponseSize: 30340237
                  totalOriginsRenderingFor: 3
                  totalRenders: 87
                  totalFailed: 2
        '400':
          description: Bad request.
          content:
            application/json:
              schema:
                type: object
                description: Bad request.
                properties:
                  status:
                    type: string
                    description: Error status.
                  message:
                    type: string
                    description: Error message.
                required:
                - status
                - message
                example:
                  status: ERROR
                  message: Header x-photoniq-customerid is required.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                description: Internal server error.
                properties:
                  status:
                    type: string
                    description: Error status.
                  message:
                    type: string
                    description: Error message.
                required:
                - status
                - message
                example:
                  status: ERROR
                  message: Internal server error.
  /api/vwr/v1/metrics/{waitingroom_key}:
    get:
      summary: Get metrics by waiting room key
      tags:
      - Metrics
      description: Allows you to retrieve waiting room telemetry per waiting room, per minute. Gets metrics for a specific waiting room. Optionally provide _start_ and _end_ filter for a specific period. Ninety days of metrics are kept.
      operationId: getMetrics
      security:
      - APIKeyAuth: []
      parameters:
      - name: waitingroom_key
        in: path
        required: true
        description: The key of the waiting room.
        schema:
          type: string
      - name: start
        in: query
        required: false
        description: The start date and time used for querying metrics data. Must be provided in RFC3339 date-time format and be in UTC.
        schema:
          type: string
          example: YYYY-MM-DDTHH:MM:SSZ
      - name: end
        in: query
        required: false
        description: The end date and time used for querying metrics data. Must be provided in RFC3339 date-time format and be in UTC.
        schema:
          type: string
          example: YYYY-MM-DDTHH:MM:SSZ
      - name: offset
        in: query
        required: false
        description: Represents the starting point from where to begin fetching the metrics records. This parameter is especially useful in conjunction with the _limit_ parameter for pagination of a large number of metrics records. By default, it is set to 0, meaning that data retrieval will start from the very first record. For example, if you have 10,000 metrics records and set the _limit_ to 100, then the first API call without an offset will retrieve records 1 to 100. If you set the _offset_ to 100 for the next call, you will retrieve records 101 to 200, and so on. This way, by incrementing the _offset_ by the _limit_ value for successive calls, you can paginate through the entire dataset.
        schema:
          type: number
          default: 0
      - name: limit
        in: query
        required: false
        description: The _limit_ parameter determines the number of metrics returned.
        schema:
          type: number
          format: number
          minimum: 1
          maximum: 1000
          default: 1000
      - name: sortby
        in: query
        required: false
        description: The field used for sorting.
        schema:
          type: string
          enum:
          - avg_waiting_time
          - waitingroom_key
          - duplicate_request_rate
          - peak_queue_length
          - queue_abandonment_rate
          - request_success_rate
          - timestamp
          - usage_requests
          default: timestamp
      - name: order
        in: query
        required: false
        description: "The sort order:\n * _asc_ - Ascending, from A to Z\n * _desc_ - Descending, from Z to A\n"
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
      responses:
        '200':
          description: Successfully fetched the metrics.
          headers:
            X-count:
              description: The total number of records.
              schema:
                type: number
                default: 1000
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RequestMetricsResponse'
              examples:
                example1:
                  value:
                  - avg_waiting_time: 800
                    waitingroom_key: test
                    duplicate_request_rate: 0
                    origin_key: test
                    peak_queue_length: 2000
                    queue_abandonment_rate: 0
                    request_success_rate: 100
                    timestamp: 1680643801
                    users_in_queue: 400000
                  - avg_waiting_time: 1000
                    waitingroom_key: virtual-room.example.io
                    duplicate_request_rate: 0
                    origin_key: example-origin
                    peak_queue_length: 3000
                    queue_abandonment_rate: 0
                    request_success_rate: 100
                    timestamp: 1680643801
                    users_in_queue: 500000
                  - avg_waiting_time: 500
                    waitingroom_key: virtual-room.example.io
                    duplicate_request_rate: 0
                    origin_key: example-origin
                    peak_queue_length: 1000
                    queue_abandonment_rate: 0
                    request_success_rate: 100
                    timestamp: 1680643741
                    users_in_queue: 60000
        '401':
          description: Authorization failure due to invalid authentication credentials.
        '403':
          description: Either the API key doesn't have permissions or it is deactivated.
        '404':
          description: Metrics not available.
        '500':
          description: Internal server error.
  /api/vwr/v1/metrics:
    get:
      summary: Get metrics
      tags:
      - Metrics
      description: Allows you to retrieve waiting room telemetry per minute. Gets metrics for all the waiting rooms. Optionally provide _start_ and _to_ filter for a specific period. Ninety days of metrics are kept.
      operationId: filterMetricsByDate
      security:
      - APIKeyAuth: []
      parameters:
      - name: start
        in: query
        required: false
        description: The start date and time used for querying metrics data. Must be provided in RFC3339 date-time format and be in UTC.
        schema:
          type: string
          example: YYYY-MM-DDTHH:MM:SSZ
      - name: end
        in: query
        required: false
        description: The end date and time used for querying metrics data. Must be provided in RFC3339 date-time format and be in UTC.
        schema:
          type: string
          example: YYYY-MM-DDTHH:MM:SSZ
      - name: offset
        in: query
        required: false
        description: Represents the starting point from where to begin fetching the metrics records. This parameter is especially useful in conjunction with the _limit_ parameter for pagination of a large number of metrics records. By default, it is set to 0, meaning that data retrieval will start from the very first record. For example, if you have 10,000 metrics records and set the _limit_ to 100, then the first API call without an offset will retrieve records 1 to 100. If you set the _offset_ to 100 for the next call, you will retrieve records 101 to 200, and so on. This way, by incrementing the _offset_ by the _limit_ value for successive calls, you can paginate through the entire dataset.
        schema:
          type: number
          default: 0
      - name: limit
        in: query
        required: false
        description: The _limit_ parameter determines the number of metrics returned.
        schema:
          type: number
          format: number
          minimum: 1
          maximum: 1000
          default: 1000
      - name: sortby
        in: query
        required: false
        description: The field used for sorting.
        schema:
          type: string
          enum:
          - avg_waiting_time
          - waitingroom_key
          - duplicate_request_rate
          - peak_queue_length
          - queue_abandonment_rate
          - request_success_rate
          - timestamp
          - usage_requests
          default: timestamp
      - name: order
        in: query
        required: false
        description: "The sort order:\n * _asc_ - Ascending, from A to Z\n * _desc_ - Descending, from Z to A\n"
        schema:
          type: string
          enum:
          - asc
          - desc
          default: asc
      responses:
        '200':
          description: Successfully fetched the metrics.
          headers:
            X-count:
              description: The total number of records.
              schema:
                type: number
                default: 1000
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RequestMetricsResponse'
              examples:
                example:
                  value:
                  - avg_waiting_time: 800
                    waitingroom_key: test
                    duplicate_request_rate: 0
                    origin_key: test
                    peak_queue_length: 2000
                    queue_abandonment_rate: 0
                    request_success_rate: 100
                    timestamp: 1680643801
                    users_in_queue: 400000
                  - avg_waiting_time: 1000
                    waitingroom_key: virtual-room.example.io
                    duplicate_request_rate: 0
                    origin_key: example-origin
                    peak_queue_length: 3000
                    queue_abandonment_rate: 0
                    request_success_rate: 100
                    timestamp: 1680643801
                    users_in_queue: 500000
                  - avg_waiting_time: 500
                    waitingroom_key: virtual-room.example.io
                    duplicate_request_rate: 0
                    origin_key: example-origin
                    peak_queue_length: 1000
                    queue_abandonment_rate: 0
                    request_success_rate: 100
                    timestamp: 1680643741
                    users_in_queue: 60000
        '400':
          description: Bad Request.
        '401':
          description: Authorization failure due to invalid authentication credentials.
        '403':
          description: Either the API key doesn't have permissions or it is deactivated.
        '500':
          description: Internal server error.
components:
  parameters:
    x-customer-id:
      name: x-customer-id
      in: header
      description: 'ID of the customer to identify the user making the request. '
      required: true
      schema:
        type: string
    sort:
      name: sort
      in: query
      description: The sort on metrics field.
      required: false
      schema:
        type: string
        nullable: true
        example: ts
    type:
      name: type
      in: query
      description: The type of the metrics data points. Supported types - sec, min, hr, day, month.
      required: false
      schema:
        type: string
        nullable: true
        example: sec
    start:
      name: start
      in: query
      description: The start date used for querying metrics data. Must be provided in RFC3339 date-time format.
      required: true
      schema:
        type: string
        example: YYYY-MM-DDTHH:MM:SSZ
    name:
      name: name
      in: query
      description: The name of the metrics data to retrieve.
      required: false
      schema:
        type: string
        nullable: true
    order:
      name: order
      in: query
      description: To arrange the metrics in ASC or DESC order.
      required: false
      schema:
        type: string
        nullable: true
        example: DESC
    end:
      name: end
      in: query
      description: The end date used for querying metrics data. Must be provided in RFC3339 date-time format.
      required: true
      schema:
        type: string
        example: YYYY-MM-DDTHH:MM:SSZ
    offset:
      name: offset
      in: query
      description: This denotes the initial number of metrics to skip in the response.
      required: false
      schema:
        type: integer
        nullable: true
        example: 0
    limit:
      name: limit
      in: query
      description: The maximum number of metrics to retrieve.
      required: false
      schema:
        type: integer
        nullable: true
        example: 100
  schemas:
    RequestMetricsResponse:
      type: object
      properties:
        avg_waiting_time:
          type: number
          format: number
          description: The average time, in milliseconds, that users spend in the virtual waiting room before being granted access to the origin service.
        waitingroom_key:
          type: string
          description: The waiting room key.
        origin_key:
          type: string
          description: The origin key.
        duplicate_request_rate:
          type: number
          format: number
          description: The percentage of duplicate requests detected and managed by the Virtual Waiting Rooms.
        peak_queue_length:
          type: number
          format: number
          description: The highest number of users in the queue during a specific period.
        queue_abandonment_rate:
          type: number
          format: number
          description: The percentage of users who leave the virtual waiting room without accessing the origin service.
        request_success_rate:
          type: number
          format: number
          description: The percentage of requests to the origin service that are successfully processed after users leave the virtual waiting room.
        timestamp:
          type: number
          format: number
          description: Unix timestamp, in seconds, of the start interval when the metric was generated.
        users_in_queue:
          type: number
          format: number
          description: The total number of users currently waiting in the virtual waiting room.
    TopNVisitorsDetails:
      type: object
      properties:
        visitorId:
          type: string
        visitorCount:
          type: number
        firstVisit:
          type: number
          format: date-time
        lastVisit:
          type: number
          format: date-time
        start:
          type: number
          format: date-time
        end:
          type: number
          format: date-time
    TopNVisitsResponse:
      type: array
      items:
        $ref: '#/components/schemas/TopNVisitorsDetails'
    TrafficResponse:
      type: array
      items:
        $ref: '#/components/schemas/TrafficDetails'
    MetricsResponse_2:
      type: array
      items:
        $ref: '#/components/schemas/MetricDetails'
    GetErrorResponse:
      type: object
      required:
      - error
      - code
      properties:
        code:
          type: integer
          format: int32
          minimum: 0
        error:
          type: string
          example: message
    DeviceTypeResponse:
      type: array
      items:
        $ref: '#/components/schemas/DeviceTypeDetails'
    MetricsResponse:
      type: object
      properties:
        cid:
          type: string
          description: customer id
        evntdlv:
          type: integer
          description: total events delivered
        evntdlvrt:
          type: number
          description: rate of event delivery per sec
        evnterrrt:
          type: number
          description: error rate per sec
        evntpub:
          type: integer
          format: int64
          description: total events published
        evntpubrt:
          type: number
          description: publish rate
        evntsz:
          type: integer
          format: int64
          description: total size of event data
        evntszrt:
          type: number
          description: rate of data sent
        fb:
          type: string
          description: fabric
        mxconn:
          type: integer
          description: max number of connections
        mxqry:
          type: integer
          description: maximum number of filters
        ssesub:
          type: integer
          description: number of active sse conn
        str:
          type: integer
          description: number of streams
        strm:
          type: array
          description: array of streams with details of each stream
          items:
            $ref: '#/components/schemas/StreamResponse'
        ts:
          type: integer
          description: timestamp
        type:
          type: string
          description: type of metric (sec, min, hr, day)
        wssub:
          type: integer
          description: number of active ws conn
    StreamResponse:
      type: object
      properties:
        stream_name:
          $ref: '#/components/schemas/StreamDetailedResponse'
    MetricDetails:
      type: object
      properties:
        _key:
          type: string
        name:
          type: string
        value:
          type: number
        start:
          type: number
          format: date-time
        end:
          type: number
          format: date-time
    DeviceTypeDetails:
      type: object
      properties:
        type:
          type: string
          example: Desktop
        count:
          type: number
          example: 50
        start:
          type: number
          format: date-time
          example: 1696965000
        end:
          type: number
          format: date-time
          example: 1696965300
    StreamDetailedResponse:
      type: object
      properties:
        conn:
          type: integer
        evntdlvrt:
          type: number
        evnterrrt:
          type: number
        evntszrt:
          type: number
        qry:
          type: integer
    TrafficDetails:
      type: object
      properties:
        human:
          type: number
          example: 1018
        goodbot:
          type: number
          example: 4
        badbot:
          type: number
          example: 10
        unknown:
          type: number
          example: 1
        start:
          type: number
          format: date-time
          example: 1696965000
        end:
          type: number
          format: date-time
          example: 1696965300
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Provide an API Key to the `Authorization` header, prefixed with "apikey".


        Example: `Authorization: apikey <key>`'
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Provide a JSON Web Token (JWT) to the `Authorization` header, prefixed with "bearer".


        Example: `Authorization: bearer <jwt>`'
